=== NADREZIM/toll_road_server/waysSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://nure.ua/borisov/SummaryTask3/task1.process.service.dataAccess.entity"
            xmlns:tns="http://nure.ua/borisov/SummaryTask3/task1.process.service.dataAccess.entity">

    <xsd:element name="startPoint" type="xsd:integer"/>
    <xsd:element name="endPoint" type="xsd:integer"/>
    <xsd:element name="fare" type="xsd:double"/>

    <xsd:element name="journey">
    <xsd:complexType>
        <xsd:sequence minOccurs="1" maxOccurs="10">
            <xsd:element name="pointOfJourney" type="tns:way"/>
                </xsd:sequence>
            </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="way">
        <xsd:sequence>
        <xsd:element ref="tns:startPoint"/>
        <xsd:element ref="tns:endPoint"/>
        <xsd:element ref="tns:fare"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== NADREZIM/toll_road_server/ways.xml
<?xml version="1.0" encoding="UTF-8"?>
<st3:journey xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:st3="http://nure.ua/borisov/SummaryTask3/task1.process.service.dataAccess.entity"
            xsi:schemaLocation="http://nure.ua/borisov/SummaryTask3/task1.process.service.dataAccess.entity waysSchema.xsd">

    <pointOfJourney>
        <st3:startPoint>1</st3:startPoint>
        <st3:endPoint>2</st3:endPoint>
        <st3:fare>20.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>2</st3:startPoint>
        <st3:endPoint>3</st3:endPoint>
        <st3:fare>21.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>3</st3:startPoint>
        <st3:endPoint>4</st3:endPoint>
        <st3:fare>22.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>4</st3:startPoint>
        <st3:endPoint>5</st3:endPoint>
        <st3:fare>23.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>5</st3:startPoint>
        <st3:endPoint>6</st3:endPoint>
        <st3:fare>24.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>6</st3:startPoint>
        <st3:endPoint>7</st3:endPoint>
        <st3:fare>25.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>7</st3:startPoint>
        <st3:endPoint>8</st3:endPoint>
        <st3:fare>26.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>8</st3:startPoint>
        <st3:endPoint>9</st3:endPoint>
        <st3:fare>27.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>9</st3:startPoint>
        <st3:endPoint>10</st3:endPoint>
        <st3:fare>28.50</st3:fare>
    </pointOfJourney>

    <pointOfJourney>
        <st3:startPoint>10</st3:startPoint>
        <st3:endPoint>1</st3:endPoint>
        <st3:fare>29.50</st3:fare>
    </pointOfJourney>

    </st3:journey>
